### ISSUE TITLE
Missing validation on non existing mines

### ISSUE THREAD

**Issue by sagile** [urigross/mineSweeper#1]
Marking a block that has no mine in it is considered as correct. 
There should be validation on marked blocks as well 
![IMG_20210523_073137](https://user-images.githubusercontent.com/10184086/119262642-262ff680-bb99-11eb-980e-43a22b2c765a.jpg)

**Comment by urigross** [comment]
Thank you for submitting Ticket No. 0353B+35353/5

Ticket Status: Closed (Fixed).

מתי שאתה בארץ תקפוץ לקפה במרפסת :)

**Comment by urigross** [comment]
Bug is closed.
